### ISSUE TITLE
settle_win / e2e_submit don't compile against the pot-era InitGame — the F↔D gap, now blocking #33's acceptance test

### ISSUE THREAD

**Issue by xAlisher** [xAlisher/lez-stark-verify#38]
`settle_win` and `e2e_submit` in `zk-guess-methods` do not compile against our own `zk-guess-program`:

```
error[E0559]: variant `Instruction::InitGame` has no field named `commitment`
  --> src/bin/settle_win.rs:92
  --> src/bin/e2e_submit.rs:82
   = note: available fields are: commitment_bytes, room_id, host_addr, host_bps, deadline_block
```

**This is not a LEZ-version problem.** Rebuilding the same bins at the old `15144ddb` (v0.2.1) pin produces byte-identical errors, so it predates the v0.2.4 bump (#33). It surfaced only now because these files were untracked until `0908ecc` and had therefore never been compiled by anyone.

### Why it matters

`settle_win` is **not** a scratch harness — it is the live win-settlement path. Its own header says:

> Env (set by the game backend's `settleOnLez`) … Prints `tx <hex>` + `block N` (the game backend parses the LAST of each as the settlement proof).

So the binary the module shells out to for "settle the win on the LEZ" has been out of sync with the program since EPIC D landed the pot (`b90553e`/`2fbc538`). `InitGame` grew `room_id`, `host_addr`, `host_bps`, `deadline_block`, and now also creates a program-owned pot PDA — while `settle_win` still calls the pre-pot signature and passes only the private game account, no pot.

**This is the concrete symptom of the F↔D gap** the project has been describing abstractly: EPIC F (on-zone settlement) and EPIC D (the pot) each work in isolation and were never reconciled.

### The actual design question (why this wasn't just fixed in #33)

Settlement only needs *seal + winning guess*. But `init_game` now **requires** creating a pot PDA, so "settle without a pot" is no longer expressible in the program's API. Someone has to decide:

1. **Settlement seals its own throwaway game** — `settle_win` supplies a derived `room_id`, `host_addr = self`, `host_bps = 0`, `deadline_block = u64::MAX`, and passes the pot account it is forced to create. Cheapest; leaves an orphan zero-value pot PDA per settlement.
2. **Split the instruction** — a pot-free `init_game` plus a separate `init_pot`, so settlement and staking stop being coupled. Cleanest, changes the deployed program.
3. **Settle against the *existing* room's game/pot** — the real F↔D integration: the winning proof releases the actual pot, which is the "last mile" already described in the halt as unfinished (payout is still a manual `vault claim`).

(3) is the intended destination; (1) is the stopgap that makes the shipped settlement path compile again. I did not pick one — guessing the semantics of a live settlement path is exactly the wrong thing to do silently.

`e2e_submit` is a plain harness and just needs to follow whatever (1)–(3) decides.

### Consequence for #33

#33's acceptance criterion — *a privacy-preserving tx from `zk-guess-program` accepted by `testnet.lez.logos.co`* — **cannot be executed yet**, because the two bins that submit PP txs are the ones that don't build. The v0.2.4 bump is verified as *compiling* everywhere (`c703c60`), but is **not yet proven against the live chain**. That proof is blocked on this issue.

The pot-era bins (`zkg_pot`, `pot_e2e`, `pot_derisk`) do compile and could carry the acceptance test instead, but they move real TOK and need a funded wallet — a deliberate call, not a side effect of a compat bump.

**Comment by xAlisher** [comment]
**Implemented as option 1, and it builds. Recorded as [ADR-0008](../blob/feat/tok-pot/docs/adr/0008-public-account-path-for-settlement.md).**

Fork commit **`71f9a4d`** on `compat/bump-lez-0.2.4` (`xAlisher/spel-lez-dev-repin`).

### What changed

Both bins move to the **public account path**, mirroring the pattern `zkg_pot`/`pot_e2e` already prove:

| before | after |
|---|---|
| `create_new_account_private` | `create_new_account_public` |
| `resolve_private_account(id)` | `AccountIdentity::Public(id)` |
| — | `AccountIdentity::PublicNoSign(pot)`, `pot = for_public_pda(pid, PdaSeed::new(room_id))` |
| `InitGame { commitment }` | `InitGame { commitment_bytes, room_id, host_addr, host_bps: 0, deadline_block: u64::MAX }` |

`room_id = SHA256(domain-prefix ‖ C)` — deterministic, and distinct per sealed number so two settlements can't collide on one PDA.

### Why public, not private

The choice wasn't arbitrary, and it turned out to matter more than "make it compile":

1. **The STARK protects the secret, not account visibility.** `secret`/`blind` are private *inputs*; the journal commits only `(commitment, guess, dir)`.
2. **`C` is already public** — broadcast to every player at seal time. A public game account discloses nothing the room doesn't have.
3. **The pot is public by construction** (PDA + auth-transfer). So a private-path settlement could *never* carry the pot account — **this is what makes the F↔D binding expressible at all** (#27). Keeping settlement private would have permanently walled off option 3.
4. **All four confirmed wallet defects live on the private path** (#39, #40). This routes settlement away from every one of them, and drops `resolve_private_account` — whose `identifier` always reads 0.

### Costs, not hidden

- Each settlement leaves an **orphan zero-value pot PDA**. Harmless litter; the honest price of option 1.
- The game account's turn log becomes **publicly readable**. Per (1)/(2) that leaks nothing new, but it is a real change in what an outside observer sees.
- Settlement still seals a **throwaway** game, so payout stays manual. **This does not close the F↔D gap — it makes closing it possible.**

### Verified

```
cargo build (zk-guess-methods, all targets)   exit 0
  settle_win, e2e_submit                      now build (were the only failures)
```

Dev-mode run against `testnet.lez.logos.co` confirms the new plumbing end-to-end up to proving — wallet init, default config, program image id, game account, **pot PDA derivation** — failing only at `ProgramProveFailed` for a missing `r0vm`, since installed.

**Not yet claimed: on-chain acceptance.** A real-proving run is in flight; #33's acceptance test is reported there, not here.

**Comment by xAlisher** [comment]
## ✅ Fully verified — closing

All three headless mechanics are now proven on the live public testnet, real proving, this session:

| mechanic | binary | result |
|---|---|---|
| **win settlement** | `settle_win` | EXIT=0, 19m04s, 2 real proofs — [tx 880a5da1…](https://testnet.lez.logos.co) block 21696, [tx 64ecb5ea…] block 21706 |
| **soundness** (wrong secret unprovable) | `e2e_submit` | EXIT=0, 17m45s, 3 real proofs — guest halts in-guest on a swapped commitment, no receipt possible |
| **full pot lifecycle** (fund → stake → win → 3-way split) | `pot_e2e` | EXIT=0, 50min, 7 real proofs — 193/100/5/2/0, independently confirmed via direct `getAccountBalance` RPC, not just the harness's own printout |

Two more real bugs turned up and were fixed along the way, both filed and one closed:
- **#44** — the SDK's default poll window (5 blocks) races real proving against ~75s testnet blocks and reports failure for settlements that actually landed. Fixed across all five bins that submit txs.
- **#45** (closed) — `BUILDER_ADDR`'s registration didn't survive the testnet's 2026-08-05 re-genesis. Fresh account minted, rebaked, and `zkg_builder_setup` made idempotent so the underlying one-shot-mint problem can't recur.

**#38 is done.** The account-model unification (ADR-0008, public path) is not just compiling — it has now moved real TOK through a real 3-way split on the actual deployed program, on the chain the game will run against. This is the precondition for the F↔D binding (#27): settlement and the pot were unreachable from each other before this, and are not anymore.

Fork: `ef3fd12` on `compat/bump-lez-0.2.4`, pushed.
